### ISSUE TITLE
Duplicated gem

### ISSUE THREAD

**Issue by deivid-rodriguez** [arkbot/guard-scss-lint#1]
Hi, I just tried you gem. It seems to work as advertised. But I noticed there's a another gem that does the same thing and it's called the same: https://github.com/chrislopresto/guard-scss-lint. That gem is the one pushed to Rubygems so the instructions in the README actually install that gem and not yours. To install yours I had to add:

```
gem 'guard-scss-lint', github: 'arkbot/guard-scss-lint'
```

to my Gemfile. Perhaps you should either talk to the other author and merge the projects or rename the gem.

Cheers!

**Comment by aeberlin** [comment]
Hey @deivid-rodriguez,

Thanks for stopping by and checking the gem out.

It seems @chrislopresto might have beaten me to it. I've been busy finalizing the test suite, which I think should be prerequisite for having anything hosted on RubyGems, and was literally planning to push the first version sometime this week.

I will contact the author and see if he would be interested in merging, as I've spent quite a bit of time getting pull requests accepted to support functionality available in other linters with guard runners. It'd be kind of a nuisance if we had to change the name and just maintain duplicate gems on the repo, but hopefully he's a sane individual and we can work together to put a unified gem out there.

I'll keep you posted. Cheers!

**Comment by chrislopresto** [comment]
@aeberlin I'll happily defer to your version.

**Comment by deivid-rodriguez** [comment]
@chrislopresto @aeberlin :+1:

**Comment by aeberlin** [comment]
Hey @chrislopresto, thank you, it's very much appreciated. If you could remove your gem from rubygems.org, I will push an alpha version today or tomorrow. In the event you had some functionality in your package not present in my gem, let me know and we'll see how to go about implementing it. Cheers!

**Comment by chrislopresto** [comment]
@aeberlin Done. Push away.

I'll switch over to your gem on my project and get back to you if I have any problems.

**Comment by aeberlin** [comment]
Wonderful, v0.0.1alpha released. Thanks, and cheers!
